# Get alpine+php7 image
FROM trafex/alpine-nginx-php7

ADD https://php.codecasts.rocks/php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub
RUN apk --update add ca-certificates
RUN echo "@php https://php.codecasts.rocks/v3.7/php-7.2" >> /etc/apk/repositories

# Install extensions
RUN apk add php7-dom php7-json php7-mbstring php7-openssl php7-phar php7-pdo php7-pdo_mysql php7-pdo_dblib php7-iconv php7-session php7-soap php7-tokenizer php7-xmlwriter php7-xml php7-zip php7-zlib

# nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

#COPY . /var/www/html
